# The names of the yum repos to use for the extensions image build.
YUM_REPO_NAMES=rhel-9.8-baseos,rhel-9.8-appstream,rhel-9.8-server-ose-5.0,rhel-9.8-highavailability,rhel-9.8-fast-datapath,rhel-9.8-nfv
